baseURL = "https://thomastay.dev/blog/"
languageCode = "en-us"
title = "Thomas Tay's blog"
theme = "yinyang"
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "monokai"
    tabWidth = 4

[author]
name = "Thomas"
homepage = "https://thomastay.dev/"

[params]
headTitle = "Thomas' weblog"
favicon="/assets/img/favicon-32x32.png"

[[params.socials]]
name = "More articles"
link = "https://thomastay.dev/blog"

[[params.socials]]
name = "Homepage"
link = "https://thomastay.dev"

[[params.socials]]
name = "Github"
link = "https://github.com/thomastay"


[[params.socials]]
name = "Linkedin"
link = "https://linkedin.com/in/thomastayac"
